name: "Continuous Integration: Releases"

on:
  push:
    branches:
    - main

concurrency: 
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v4
      name: Checkout
  
    - uses: jefflinse/pr-semver-bump@v1.7.0
      name: Bump and Tag Version
      id: semver
      with:
        mode: bump
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        major-label: SemVer Major
        minor-label: SemVer Minor
        patch-label: SemVer Patch
        noop-labels: SemVer Skip
        require-release-notes: true
        release-notes-prefix: "# Release Notes:"
        release-notes-suffix: "<sub>_End Release Notes_</sub>"
        with-v: true
        base-branch: false

    - name: Debug the Output
      run: |

        echo "old-version          - ${{ steps.semver.outputs.old-version }}"
        echo "version              - ${{ steps.semver.outputs.version }}"
        echo "skipped              - ${{ steps.semver.outputs.skipped }}"
        echo "semver_release-notes - ${{ steps.semver.outputs.semver_release-notes }}"

    outputs:
      semver_old: ${{ steps.semver.outputs.old-version }}
      semver_next: ${{ steps.semver.outputs.version }}
      semver_skipped: ${{ steps.semver.outputs.skipped }}
      semver_release-notes: ${{ steps.semver.outputs.release-notes }}


  build:
    name: Build Release
    if: ${{ needs.bump-tag-version.outputs.semver_skipped == 'false' }}
    runs-on: windows-latest
    needs: bump-tag-version

    steps:
    - uses: actions/checkout@v4
      name: Checkout Source
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Debug the Output
      run: |

        echo "old-version          - ${{ needs.bump-tag-version.outputs.semver_old }}"
        echo "version              - ${{ needs.bump-tag-version.outputs.semver_next }}"
        echo "skipped              - ${{ needs.bump-tag-version.outputs.semver_skipped }}"
        echo "semver_release-notes - ${{ needs.bump-tag-version.outputs.semver_release-notes }}"

    - uses: ./.github/actions/build/
      name: Build Release

    - name: Make Release Directory
      run: mkdir ${{ github.workspace }}/_release

    - name: Compress Build
      run: |
        $compress = @{
          Path = "${{ github.workspace }}/_build/*"
          CompressionLevel = "Fastest"
          DestinationPath = "${{ github.workspace }}/_release/sssv_${{ needs.bump-tag-version.outputs.semver_next }}.zip"
        }
        Compress-Archive @compress

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.workspace }}/_release/sots-sge_${{ needs.bump-tag-version.outputs.semver_next }}.zip"
        body: "${{ needs.bump-tag-version.outputs.semver_release-notes }}"
        makeLatest: true
        tag: ${{ needs.bump-tag-version.outputs.semver_next }}
        name: Release ${{ needs.bump-tag-version.outputs.semver_next }}
